biomede-211-w19.tex

Added a description to section 1.3.3

Update 1.3.3: "The 'speed' of current"

---

biomede-211-w19.tex

Explanations of active/ passive elements and Ohm's Law

Active, Passive, and Ohm's Law

---

biomede-211-w19.tex

added an explanation of resistors, resistance, and resistivity

update to resistors section

---

biomede-211-w19.tex

For the op-amps examples, I have added in the calculations done for each of the three examples- inverting amplifier, non-inverting amplifier, and the voltage buffer.

Transistors, op-amps examples

---

biomede-211-w19.tex

Pretty much a calc derivation for the same equation(s) that was reached in the above subsection. This may be a bit much...
The part that was actually changed was line 375

Slightly Redundant RC Circuit Charge Equation

---

biomede-211-w19.tex

I have added the notes from class for both nodes and branches and Kirchhoff's Laws

Chapter 4: notes for 4.1/4.2

---

biomede-211-w19.tex

Paragraph added beginning at line 168 about differences between voltage and current

Added paragraph about current vs. potential

---

biomede-211-w19.tex

A microscopic view of current in a cylindrical wire with the concept of drift velocity.

Change made from line 154 to 159 by Hao Shen

---

biomede-211-w19.tex

Added link to a quizlet that I created to study from (with terms, equations and units). https://quizlet.com/_60f6w7

AddedStudyResource (Quizlet)

---

biomede-211-w19.tex

I have added 2 youtube videos on the laplace transform.  The first one explain the laplace transform in a visual 3D way and the second one elaborates on the RLC laplace transforms we explored in class.

Ch10- Additional Recourses

---

biomede-211-w19.tex

Alec Sunshine edit

---

biomede-211-w19.tex

definitions and specifications for various ion channels and electrocardiography

Lecture 18 material

---

biomede-211-w19.tex

“The Theory and Fundamentals of Bioimpedance Analysis in Clinical Status Monitoring and Diagnosis of Diseases”
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4118362/ 
Advantages of bioimpedance measurements: 
-low cost
-portable systems
-wide range of utilizations, non-invasive
Definition of Bioimpedance: the ability of biological tissue to impede electric current
Active vs. Passive Response:
Active: Biological tissues provoke electricity on their own from ionic activities inside cells (for example, electrocardiogram signals from the heart)
Passive: Biological tissues are stimulated through an external electrical current source; an elicited reaction to a stimulus.
Methods for measuring whole-body impedance using different placements and types of electrodes:
Hand to foot method: gel-filled …

Additional Information on Bioimpedance

---

biomede-211-w19.tex

Notes were on cell biopotential modeling components and ECG Hardware Components

Added notes for some of the Biopotential Lecture (4/4)

---

biomede-211-w19.tex

Added 4/2/19 Board Images

---

biomede-211-w19.tex

Uploaded 3/26/19 Board Pictures

---

biomede-211-w19.tex

I emailed you about adding a project that I had where I modeled the Hodgkin Huxley nobel prize paper and I turned it into a latex file and added it. I am not sure how it will appear in the pdf version so if this doesn't work I can add a link instead !

Adding Hodgkin Huxley Simulation

---

biomede-211-w19.tex

I added the board pictures as well as images of my notes, because some of the pictures werent very clear

Adding board pictures

---

biomede-211-w19.tex

I added information on electrophysiology for the EEG, EOG, EMG, and EGG sections gone over during lecture on 4/4/2019

Added information on electrophysiology 4/4/2019

---

biomede-211-w19.tex

Fixed a lot of formatting issues that were resulting in equations being displayed incorrectly.

Formatting

---

biomede-211-w19.tex

I added examples of medical devices for each of the classifications (Class I, Class II, Class III). I wanted to find some examples for my own understanding and thought that it might be helpful for others to see the types of medical devices that fall under these categories.

Added examples of medical device classifications

---

biomede-211-w19.tex

a website with explanation, simple examples, complicated examples, and a quiz.

Logic Gates

---

biomede-211-w19.tex

I added the Laplace transforms of a unit step function, unit impulse function and the unit ramp function. I also added a description of the "sifting" abilities of the unit impulse function.

Updated "Circuits as ODE's : First Order"

---

biomede-211-w19.tex

Apologies for the earlier inconveniences. I have copy and pasted the review problems in the new text file

Resubmition of Final Exam practice

---

biomede-211-w19.tex

I added a useful video link for understanding various properties of the unit impulse function.

Added a Useful Video Link

---

biomede-211-w19.tex

I added a short youtube tutorial that aided me in making knights and knaves logic problems into a truth table to then create a logic gate with

Added Youtube tutorial

---

biomede-211-w19.tex

I have added a page that encompasses what was discussed in the lecture before our 3rd Glorified Quiz and I have also included information that relates to other world powers and how they regulate medical devices

Medical legislation page
